__title__ = 'PyGeoDiff'
__description__ = 'Diff tool for geo-spatial data'
__url__ = 'https://github.com/MerginMaps/geodiff'
# use scripts/update_version.py to update the version here and in other places at once
__version__ = '2.0.1'
__author__ = 'Lutra Consulting Ltd.'
__author_email__ = 'info@merginmaps.com'
__maintainer__ = 'Lutra Consulting Ltd.'
__license__ = 'MIT'
__copyright__ = '(c) 2019-2022 Lutra Consulting Ltd.'
