__title__ = 'PyGeoDiff'
__description__ = 'Diff tool for geo-spatial data'
__url__ = 'https://github.com/lutraconsulting/geodiff'
# use scripts/update_version.py to update the version here and in other places at once
__version__ = '1.0.6'
__author__ = 'Peter Petrik'
__author_email__ = 'zilolv@gmail.com'
__maintainer__ = 'Peter Petrik'
__license__ = 'MIT'
__copyright__ = '(c) 2019-2021 Peter Petrik'
