name: Code Layout
on: [push]
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Install astyle
        run: |
          sudo apt-get install astyle

      - uses: actions/checkout@v2

      - name: Run astyle check
        run: |
          cd scripts
          ./run_astyle.sh `find ../geodiff -name \*.h* -print -o -name \*.c* -print`

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Requirements
        run: |
          sudo apt install -y cppcheck
      - name: Run cppcheck test
        run: |
          ./scripts/run_cppcheck.sh