name: Code Layout
on: [push]
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Install astyle
        run: |
          sudo apt-get install astyle

      - uses: actions/checkout@v2

      - name: Run astyle check
        run: |
          cd scripts
          ./run_astyle.sh `find ../geodiff -name \*.h* -print -o -name \*.c* -print`
