name: Coverage Tests
on: [push]
jobs:
  tests:
    if: github.repository == 'lutraconsulting/geodiff'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Geodiff
        uses: actions/checkout@v2

      - name: install deps
        run: |
          - sudo apt-get install libsqlite3-dev libpq-dev

      - name: build geodiff with coverage
        run: |
          - mkdir -p build_coverage_lnx
          - cd build_coverage_lnx
          - cmake \
              -DCMAKE_BUILD_TYPE=Debug \
              -DENABLE_TESTS=ON \
              -DENABLE_COVERAGE=ON \
              -DWITH_POSTGRESQL=TRUE \
              -DWITH_INTERNAL_SQLITE3=FALSE \
              ..
          - make

      - name: Run tests
        env:
          CTEST_TARGET_SYSTEM: Linux-gcc
        run: |
          - cd build_coverage_lnx
          - ctest -VV

      - name: Prepare coverage report
        run: |
          cd build_coverage_lnx
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/tests/*' '/usr/*' '*googletest/*' '*/3rdparty/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: build_coverage_lnx/coverage.info